[build]
  command = "npm run build"
  publish = "dist/client"

[[redirects]]
  from = "/_serverFn/*"
  to = "/_serverFn/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/_shell.html"
  status = 200
