/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as NewVsUsedRouteImport } from './routes/new-vs-used'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryPlacementInfoRouteImport } from './routes/delivery-placement-info'
import { Route as ContainerSizesRouteImport } from './routes/container-sizes'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuyersGuideRouteImport } from './routes/buyers-guide'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const NewVsUsedRoute = NewVsUsedRouteImport.update({
  id: '/new-vs-used',
  path: '/new-vs-used',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryPlacementInfoRoute = DeliveryPlacementInfoRouteImport.update({
  id: '/delivery-placement-info',
  path: '/delivery-placement-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ContainerSizesRoute = ContainerSizesRouteImport.update({
  id: '/container-sizes',
  path: '/container-sizes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersGuideRoute = BuyersGuideRouteImport.update({
  id: '/buyers-guide',
  path: '/buyers-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyers-guide': typeof BuyersGuideRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/container-sizes': typeof ContainerSizesRoute
  '/delivery-placement-info': typeof DeliveryPlacementInfoRoute
  '/faq': typeof FaqRoute
  '/new-vs-used': typeof NewVsUsedRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyers-guide': typeof BuyersGuideRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/container-sizes': typeof ContainerSizesRoute
  '/delivery-placement-info': typeof DeliveryPlacementInfoRoute
  '/faq': typeof FaqRoute
  '/new-vs-used': typeof NewVsUsedRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/buyers-guide': typeof BuyersGuideRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/container-sizes': typeof ContainerSizesRoute
  '/delivery-placement-info': typeof DeliveryPlacementInfoRoute
  '/faq': typeof FaqRoute
  '/new-vs-used': typeof NewVsUsedRoute
  '/shop': typeof ShopRoute
  '/testimonials': typeof TestimonialsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$slug': typeof ProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/buyers-guide'
    | '/cart'
    | '/contact'
    | '/container-sizes'
    | '/delivery-placement-info'
    | '/faq'
    | '/new-vs-used'
    | '/shop'
    | '/testimonials'
    | '/category/$slug'
    | '/product/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/buyers-guide'
    | '/cart'
    | '/contact'
    | '/container-sizes'
    | '/delivery-placement-info'
    | '/faq'
    | '/new-vs-used'
    | '/shop'
    | '/testimonials'
    | '/category/$slug'
    | '/product/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/buyers-guide'
    | '/cart'
    | '/contact'
    | '/container-sizes'
    | '/delivery-placement-info'
    | '/faq'
    | '/new-vs-used'
    | '/shop'
    | '/testimonials'
    | '/category/$slug'
    | '/product/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuyersGuideRoute: typeof BuyersGuideRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  ContainerSizesRoute: typeof ContainerSizesRoute
  DeliveryPlacementInfoRoute: typeof DeliveryPlacementInfoRoute
  FaqRoute: typeof FaqRoute
  NewVsUsedRoute: typeof NewVsUsedRoute
  ShopRoute: typeof ShopRoute
  TestimonialsRoute: typeof TestimonialsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-vs-used': {
      id: '/new-vs-used'
      path: '/new-vs-used'
      fullPath: '/new-vs-used'
      preLoaderRoute: typeof NewVsUsedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-placement-info': {
      id: '/delivery-placement-info'
      path: '/delivery-placement-info'
      fullPath: '/delivery-placement-info'
      preLoaderRoute: typeof DeliveryPlacementInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/container-sizes': {
      id: '/container-sizes'
      path: '/container-sizes'
      fullPath: '/container-sizes'
      preLoaderRoute: typeof ContainerSizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers-guide': {
      id: '/buyers-guide'
      path: '/buyers-guide'
      fullPath: '/buyers-guide'
      preLoaderRoute: typeof BuyersGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuyersGuideRoute: BuyersGuideRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  ContainerSizesRoute: ContainerSizesRoute,
  DeliveryPlacementInfoRoute: DeliveryPlacementInfoRoute,
  FaqRoute: FaqRoute,
  NewVsUsedRoute: NewVsUsedRoute,
  ShopRoute: ShopRoute,
  TestimonialsRoute: TestimonialsRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
